services:
  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    env_file: ./.env
    networks:
      - app-network
    depends_on:
      postgres-db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && echo 'Migration complete' && exit 0"

  app:
    build: .
    env_file: ./.env
    networks:
      - app-network
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      migrations:
        condition: service_completed_successfully
      postgres-db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npm start"

networks:
  app-network:

volumes:
  postgres-data:
